evaluate: evaluate.cpp
	g++ evaluate.cpp -o evaluate

helping : helping.cpp
	g++ helping.cpp -o helping

runHelping: helping
	
	./helping 1.txt

run: evaluate

	./evaluate 1.txt 0 1 1
	./evaluate 2.txt 0 1 1
	./evaluate 3.txt 0 1 0
	./evaluate 4.txt 1 0 0 0 1
