trust : trust.cpp
	g++ trust.cpp -o trust

run: trust
	./trust < inputs/1.txt >outputs/1.txt
	./trust < inputs/2.txt >outputs/2.txt
	./trust < inputs/3.txt >outputs/3.txt
	./trust < inputs/4.txt >outputs/4.txt
	./trust < inputs/5.txt >outputs/5.txt
	./trust < inputs/6.txt >outputs/6.txt
	./trust < inputs/7.txt >outputs/7.txt
	./trust < inputs/9.txt >outputs/9.txt
	./trust < inputs/8.txt >outputs/8.txt